[build]
  base = "."
  publish = "dist/spa"
  command = "yarn build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[images]
  remote_images = ["https://ipfs.pintastic.link/ipfs/.*"]
