// generated by @greymass/abi2core

import { Asset, Checksum256, ExtendedAsset, Name, Struct, TimePointSec, UInt64 } from "@greymass/eosio"

@Struct.type("Config")
export class Config extends Struct {
    @Struct.field(ExtendedAsset) min_fee!:ExtendedAsset
}

@Struct.type("IbcOrder")
export class IbcOrder extends Struct {
    @Struct.field(UInt64) id!:UInt64
    @Struct.field(Name) depositor!:Name
    @Struct.field(TimePointSec) deposited_time!:TimePointSec
    @Struct.field(Asset) fee_paid!:Asset
    @Struct.field(Checksum256) ibc_relay_trxid!:Checksum256
}

@Struct.type("clearconfig")
export class Clearconfig extends Struct {
}

@Struct.type("rmorder")
export class Rmorder extends Struct {
    @Struct.field(UInt64) order_id!:UInt64
}

@Struct.type("setconfig")
export class Setconfig extends Struct {
    @Struct.field(Config) config!:Config
}
