// generated by @greymass/abi2core

import {
  Asset,
  BlockTimestamp,
  Bytes,
  Checksum256,
  ExtendedAsset,
  Name,
  PublicKey,
  Signature,
  Struct,
  UInt16,
  UInt32,
  UInt64,
  VarUInt
} from "@greymass/eosio"

@Struct.type("account")
export class Account extends Struct {
  @Struct.field(Asset) balance!:Asset
}

@Struct.type("permission_level")
export class PermissionLevel extends Struct {
  @Struct.field(Name) actor!:Name
  @Struct.field(Name) permission!:Name
}

@Struct.type("action")
export class Action extends Struct {
  @Struct.field(Name) account!:Name
  @Struct.field(Name) name!:Name
  @Struct.field(PermissionLevel, { array: true }) authorization!:PermissionLevel[]
  @Struct.field(Bytes) data!:Bytes
}

@Struct.type("authseq")
export class Authseq extends Struct {
  @Struct.field(Name) account!:Name
  @Struct.field(UInt64) sequence!:UInt64
}

@Struct.type("actreceipt")
export class Actreceipt extends Struct {
  @Struct.field(Name) receiver!:Name
  @Struct.field(Checksum256) act_digest!:Checksum256
  @Struct.field(UInt64) global_sequence!:UInt64
  @Struct.field(UInt64) recv_sequence!:UInt64
  @Struct.field(Authseq, { array: true }) auth_sequence!:Authseq[]
  @Struct.field(VarUInt) code_sequence!:VarUInt
  @Struct.field(VarUInt) abi_sequence!:VarUInt
}

@Struct.type("actionproof")
export class Actionproof extends Struct {
  @Struct.field(Action) action!:Action
  @Struct.field(Actreceipt) receipt!:Actreceipt
  @Struct.field(Bytes) returnvalue!:Bytes
  @Struct.field(Checksum256, { array: true }) amproofpath!:Checksum256[]
}

@Struct.type("producer_key")
export class ProducerKey extends Struct {
  @Struct.field(Name) producer_name!:Name
  @Struct.field(PublicKey) block_signing_key!:PublicKey
}

@Struct.type("producer_schedule")
export class ProducerSchedule extends Struct {
  @Struct.field(UInt32) version!:UInt32
  @Struct.field(ProducerKey, { array: true }) producers!:ProducerKey[]
}

@Struct.type("pair_uint16_bytes")
export class PairUint16Bytes extends Struct {
  @Struct.field(UInt16) first!:UInt16
  @Struct.field(Bytes) second!:Bytes
}

@Struct.type("blockheader")
export class Blockheader extends Struct {
  @Struct.field(BlockTimestamp) timestamp!:BlockTimestamp
  @Struct.field(Name) producer!:Name
  @Struct.field(UInt16) confirmed!:UInt16
  @Struct.field(Checksum256) previous!:Checksum256
  @Struct.field(Checksum256) transaction_mroot!:Checksum256
  @Struct.field(Checksum256) action_mroot!:Checksum256
  @Struct.field(UInt32) schedule_version!:UInt32
  @Struct.field(ProducerSchedule, { optional: true }) new_producers?:ProducerSchedule
  @Struct.field(PairUint16Bytes, { array: true }) header_extensions!:PairUint16Bytes[]
}

@Struct.type("sblockheader")
export class Sblockheader extends Struct {
  @Struct.field(Blockheader) header!:Blockheader
  @Struct.field(Signature, { array: true }) producer_signatures!:Signature[]
  @Struct.field(Checksum256) previous_bmroot!:Checksum256
  @Struct.field(UInt16, { array: true }) bmproofpath!:UInt16[]
}

@Struct.type("anchorblock")
export class Anchorblock extends Struct {
  @Struct.field(Sblockheader) block!:Sblockheader
  @Struct.field(UInt16, { array: true }) active_nodes!:UInt16[]
  @Struct.field(UInt64) node_count!:UInt64
}

@Struct.type("heavyproof")
export class Heavyproof extends Struct {
  @Struct.field(Checksum256) chain_id!:Checksum256
  @Struct.field(Checksum256, { array: true }) hashes!:Checksum256[]
  @Struct.field(Anchorblock) blocktoprove!:Anchorblock
  @Struct.field(Sblockheader, { array: true }) bftproof!:Sblockheader[]
}

@Struct.type("cancela")
export class Cancela extends Struct {
  @Struct.field(Name) prover!:Name
  @Struct.field(Heavyproof) blockproof!:Heavyproof
  @Struct.field(Actionproof) actionproof!:Actionproof
}

@Struct.type("lightproof")
export class Lightproof extends Struct {
  @Struct.field(Checksum256) chain_id!:Checksum256
  @Struct.field(Blockheader) header!:Blockheader
  @Struct.field(Checksum256) root!:Checksum256
  @Struct.field(Checksum256, { array: true }) bmproofpath!:Checksum256[]
}

@Struct.type("cancelb")
export class Cancelb extends Struct {
  @Struct.field(Name) prover!:Name
  @Struct.field(Lightproof) blockproof!:Lightproof
  @Struct.field(Actionproof) actionproof!:Actionproof
}

@Struct.type("close")
export class Close extends Struct {
  @Struct.field(Name) owner!:Name
  @Struct.field(Asset.Symbol) symbol!:Asset.Symbol
}

@Struct.type("currency_stats")
export class CurrencyStats extends Struct {
  @Struct.field(Asset) supply!:Asset
  @Struct.field(Asset) max_supply!:Asset
  @Struct.field(Name) issuer!:Name
}

@Struct.type("disable")
export class Disable extends Struct {
}

@Struct.type("xfer")
export class Xfer extends Struct {
  @Struct.field(Name) owner!:Name
  @Struct.field(ExtendedAsset) quantity!:ExtendedAsset
  @Struct.field(Name) beneficiary!:Name
}

@Struct.type("emitxfer")
export class Emitxfer extends Struct {
  @Struct.field(Xfer) xfer!:Xfer
}

@Struct.type("enable")
export class Enable extends Struct {
}

@Struct.type("global")
export class Global extends Struct {
  @Struct.field(Checksum256) chain_id!:Checksum256
  @Struct.field(Name) bridge_contract!:Name
  @Struct.field(Checksum256) paired_chain_id!:Checksum256
  @Struct.field(Name) paired_wraplock_contract!:Name
  @Struct.field(Name) paired_token_contract!:Name
  @Struct.field("bool") enabled!:boolean
}

@Struct.type("hpstruct")
export class Hpstruct extends Struct {
  @Struct.field(UInt64) id!:UInt64
  @Struct.field(Heavyproof) hp!:Heavyproof
}

@Struct.type("init")
export class Init extends Struct {
  @Struct.field(Checksum256) chain_id!:Checksum256
  @Struct.field(Name) bridge_contract!:Name
  @Struct.field(Checksum256) paired_chain_id!:Checksum256
  @Struct.field(Name) paired_wraplock_contract!:Name
  @Struct.field(Name) paired_token_contract!:Name
}

@Struct.type("issuea")
export class Issuea extends Struct {
  @Struct.field(Name) prover!:Name
  @Struct.field(Heavyproof) blockproof!:Heavyproof
  @Struct.field(Actionproof) actionproof!:Actionproof
}

@Struct.type("issueb")
export class Issueb extends Struct {
  @Struct.field(Name) prover!:Name
  @Struct.field(Lightproof) blockproof!:Lightproof
  @Struct.field(Actionproof) actionproof!:Actionproof
}

@Struct.type("lpstruct")
export class Lpstruct extends Struct {
  @Struct.field(UInt64) id!:UInt64
  @Struct.field(Lightproof) lp!:Lightproof
}

@Struct.type("open")
export class Open extends Struct {
  @Struct.field(Name) owner!:Name
  @Struct.field(Asset.Symbol) symbol!:Asset.Symbol
  @Struct.field(Name) ram_payer!:Name
}

@Struct.type("processed")
export class Processed extends Struct {
  @Struct.field(UInt64) id!:UInt64
  @Struct.field(Checksum256) receipt_digest!:Checksum256
}

@Struct.type("retire")
export class Retire extends Struct {
  @Struct.field(Name) owner!:Name
  @Struct.field(Asset) quantity!:Asset
  @Struct.field(Name) beneficiary!:Name
}

@Struct.type("transfer")
export class Transfer extends Struct {
  @Struct.field(Name) from!:Name
  @Struct.field(Name) to!:Name
  @Struct.field(Asset) quantity!:Asset
  @Struct.field("string") memo!:string
}
